import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
      <div style={{width: '100%', height: '50px', background: 'yellow'}}></div>
        {children}
        <footer style={{width: '100%', height: '50px', background: 'green'}}></footer>
        </body>
    </html>
  )
}
